name = input("Enter your name: ")
age = input("Enter your age: ")
print(f"Your name is {name}")
print(f"Your name is {age}")
print(f"The name type is: {type(name)}")
print(f"The name age is: {type(age)}")
